# Generated by Django 2.2.24 on 2021-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeetups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
