# Generated by Django 2.2.24 on 2021-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeetups', '0003_meetup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organiser',
            field=models.EmailField(default='2021-10-11', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='mymeetups.Participant'),
        ),
    ]
